### ISSUE TITLE
star.gr/tv/shows/masterchef/

### ISSUE THREAD

**Issue by AngelosNaoumis** [kargig/greek-adblockplus-filter#49] opened 2019-03-22 22:34 UTC
There is a problem with star's channel (masterchef) video player.
When you go from player to full screen it just goes black.
Preview: https://i.imgur.com/WOJYTQN.png

When I disable the filter, the problem is fixed.

What is my setup?
Firefox: 66
Nano adblocker: last version

**Comment by kargig** [comment] 2019-03-23 12:54
works for me on firefox + google chrome w/ ublock origin.
I can't help more unless you tell which exact urls/elements are getting blocked, and if any of these are being blocked by this filter.

Does it work when you disable the greek filter or when you disable all filters ?

This are the blocked elements on my setup where video playback still works:
![image](https://user-images.githubusercontent.com/613783/54866342-352d7b00-4d7b-11e9-8413-f000dcb7189a.png)

**Comment by AngelosNaoumis** [comment] 2019-03-23 16:02
Update on this: 
Going from normal view (on videos) to full screen I got a black video player
Going from normal view -> full screen -> back to normal view -> full screen fixes the problem.

I am gonna investigate further, I do not think it is the filter who is messing with it.

**Comment by kargig** [comment] 2019-03-23 17:51
I'll close this issue then as the problem is irrelevant with the current filters.
Thanks for the feedback anyway

**Closed by kargig** 2019-03-23 17:51 UTC
